version: '2'
services:
  web:
    image: app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    environment:
      SEQ_DB: fitcoin
      SEQ_USER: docker
      SEQ_PW: docker
      DATABASE_URL: postgres://docker:docker@db:5432/fitcoin
    depends_on:
      - "db"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fitcoin
  redis:
    image: redis
